### PR TITLE
Standard alignment

### PR DESCRIPTION
**Pull request by oreleraki**
Added: Support for cross platform deletion using rimraf, instead of rm -rf

Added: 2 additional npm script, for development: 'build-dev' and 'start-dev'

Changed: deleted output directory 'prod' from source control + Changed the output directory to be 'dist' + startup file is now 'index.js'

### CODE REVIEW

**Review by taranvohra — COMMENTED** [review]
`clean` should also delete `generated`. The generated folder is where the top10 stats images gets pushed onto. 

When running in production mode, wouldn't it be a good idea to add source maps there too? The logs will point to the babel transpiled code otherwise and it's almost unreadable

**Comment by oreleraki** [comment]
I will add the removal of `generated`.
About source maps, i'm coming from the web development world, and it's usually not a good idea to leave source maps on production sites. But if you're happy with them, we can leave them.
Make a choice and tell me

**Comment by taranvohra** [comment]
Yes, I'm aware of that but in web you're downloading the JS code already whereas that's not the case here. It usually helps me debug alot of bugs when running in production.

**Comment by oreleraki** [comment]
And you're not preferring to use the "npm run start-dev" in production, for debug. But others that are running for production will not have it ?

**Comment by taranvohra** [comment]
Well that's a good argument, I think that does it

**Pull request merged**
