### PR TITLE
Added: Config file

### PR DESCRIPTION
**Pull request by oreleraki**

### CODE REVIEW

**Review by taranvohra — COMMENTED** [review]
I have thought about this and theres a reason why I haven't gone with it and used environment variables. If you dockerize the application (which I'm planning to do so in the future), I can supply bot token, db hosts, passwords, etc through ENV variables when I'm about to run the container. 

However if i proceed with a .json, then my docker image will be built with that and if i want to change something then it will require a new build everytime which is more time consuming.

**Comment by oreleraki** [comment]
That is my thought as well, for the long term solution i'm thinking of docker file which writes the `config.json` and the docker image can run freely.
What your thoughts of this style ?

**Comment by taranvohra** [comment]
It's pretty risky still because docker images can be reverse engineered easily hence it's not a great idea to pack sensitive information with it.

**Comment by oreleraki** [comment]
I don't mean the docker image, but the docker file, the file which build the image and apply settings: it can be process.env or create config file from settings in the docker file.

Do you want me to close this commit ?

**Comment by taranvohra** [comment]
Yes but when you eventually build the images, the config.json will be packed into it and theres sensitive information in it. I'd say yeah we can close this for now as theres more to think about this

**Comment by oreleraki** [comment]
Ok i will close this, and i will do a small change, but it will still use the same process.ENV arguments.

**Pull request closed without merging**
